# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from tbp.simulator.protocol.v1 import protocol_pb2 as tbp_dot_simulator_dot_protocol_dot_v1_dot_protocol__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in tbp/simulator/protocol/v1/protocol_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SimulatorServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RemoveAllObjects = channel.unary_unary(
                '/tbp.simulator.protocol.v1.SimulatorService/RemoveAllObjects',
                request_serializer=tbp_dot_simulator_dot_protocol_dot_v1_dot_protocol__pb2.RemoveAllObjectsRequest.SerializeToString,
                response_deserializer=tbp_dot_simulator_dot_protocol_dot_v1_dot_protocol__pb2.RemoveAllObjectsResponse.FromString,
                _registered_method=True)
        self.AddObject = channel.unary_unary(
                '/tbp.simulator.protocol.v1.SimulatorService/AddObject',
                request_serializer=tbp_dot_simulator_dot_protocol_dot_v1_dot_protocol__pb2.AddObjectRequest.SerializeToString,
                response_deserializer=tbp_dot_simulator_dot_protocol_dot_v1_dot_protocol__pb2.AddObjectResponse.FromString,
                _registered_method=True)
        self.Step = channel.unary_unary(
                '/tbp.simulator.protocol.v1.SimulatorService/Step',
                request_serializer=tbp_dot_simulator_dot_protocol_dot_v1_dot_protocol__pb2.StepRequest.SerializeToString,
                response_deserializer=tbp_dot_simulator_dot_protocol_dot_v1_dot_protocol__pb2.StepResponse.FromString,
                _registered_method=True)
        self.Reset = channel.unary_unary(
                '/tbp.simulator.protocol.v1.SimulatorService/Reset',
                request_serializer=tbp_dot_simulator_dot_protocol_dot_v1_dot_protocol__pb2.ResetRequest.SerializeToString,
                response_deserializer=tbp_dot_simulator_dot_protocol_dot_v1_dot_protocol__pb2.ResetResponse.FromString,
                _registered_method=True)
        self.Close = channel.unary_unary(
                '/tbp.simulator.protocol.v1.SimulatorService/Close',
                request_serializer=tbp_dot_simulator_dot_protocol_dot_v1_dot_protocol__pb2.CloseRequest.SerializeToString,
                response_deserializer=tbp_dot_simulator_dot_protocol_dot_v1_dot_protocol__pb2.CloseResponse.FromString,
                _registered_method=True)


class SimulatorServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RemoveAllObjects(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddObject(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Step(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Reset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Close(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SimulatorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RemoveAllObjects': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveAllObjects,
                    request_deserializer=tbp_dot_simulator_dot_protocol_dot_v1_dot_protocol__pb2.RemoveAllObjectsRequest.FromString,
                    response_serializer=tbp_dot_simulator_dot_protocol_dot_v1_dot_protocol__pb2.RemoveAllObjectsResponse.SerializeToString,
            ),
            'AddObject': grpc.unary_unary_rpc_method_handler(
                    servicer.AddObject,
                    request_deserializer=tbp_dot_simulator_dot_protocol_dot_v1_dot_protocol__pb2.AddObjectRequest.FromString,
                    response_serializer=tbp_dot_simulator_dot_protocol_dot_v1_dot_protocol__pb2.AddObjectResponse.SerializeToString,
            ),
            'Step': grpc.unary_unary_rpc_method_handler(
                    servicer.Step,
                    request_deserializer=tbp_dot_simulator_dot_protocol_dot_v1_dot_protocol__pb2.StepRequest.FromString,
                    response_serializer=tbp_dot_simulator_dot_protocol_dot_v1_dot_protocol__pb2.StepResponse.SerializeToString,
            ),
            'Reset': grpc.unary_unary_rpc_method_handler(
                    servicer.Reset,
                    request_deserializer=tbp_dot_simulator_dot_protocol_dot_v1_dot_protocol__pb2.ResetRequest.FromString,
                    response_serializer=tbp_dot_simulator_dot_protocol_dot_v1_dot_protocol__pb2.ResetResponse.SerializeToString,
            ),
            'Close': grpc.unary_unary_rpc_method_handler(
                    servicer.Close,
                    request_deserializer=tbp_dot_simulator_dot_protocol_dot_v1_dot_protocol__pb2.CloseRequest.FromString,
                    response_serializer=tbp_dot_simulator_dot_protocol_dot_v1_dot_protocol__pb2.CloseResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tbp.simulator.protocol.v1.SimulatorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tbp.simulator.protocol.v1.SimulatorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SimulatorService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RemoveAllObjects(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tbp.simulator.protocol.v1.SimulatorService/RemoveAllObjects',
            tbp_dot_simulator_dot_protocol_dot_v1_dot_protocol__pb2.RemoveAllObjectsRequest.SerializeToString,
            tbp_dot_simulator_dot_protocol_dot_v1_dot_protocol__pb2.RemoveAllObjectsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddObject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tbp.simulator.protocol.v1.SimulatorService/AddObject',
            tbp_dot_simulator_dot_protocol_dot_v1_dot_protocol__pb2.AddObjectRequest.SerializeToString,
            tbp_dot_simulator_dot_protocol_dot_v1_dot_protocol__pb2.AddObjectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Step(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tbp.simulator.protocol.v1.SimulatorService/Step',
            tbp_dot_simulator_dot_protocol_dot_v1_dot_protocol__pb2.StepRequest.SerializeToString,
            tbp_dot_simulator_dot_protocol_dot_v1_dot_protocol__pb2.StepResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Reset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tbp.simulator.protocol.v1.SimulatorService/Reset',
            tbp_dot_simulator_dot_protocol_dot_v1_dot_protocol__pb2.ResetRequest.SerializeToString,
            tbp_dot_simulator_dot_protocol_dot_v1_dot_protocol__pb2.ResetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Close(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tbp.simulator.protocol.v1.SimulatorService/Close',
            tbp_dot_simulator_dot_protocol_dot_v1_dot_protocol__pb2.CloseRequest.SerializeToString,
            tbp_dot_simulator_dot_protocol_dot_v1_dot_protocol__pb2.CloseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
